services:
  jenkins:
    container_name: jenkins
    images: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins:/var/jenkins_home"
    networks:
        - net
networks:
  net:
